### PR TITLE
Fix for Windows-based servers

### PR DESCRIPTION
**Pull request by gabidj**
Fix for Windows-based servers
Remove all occurrences of `"`

### CODE REVIEW

**Comment by gabidj** [comment]
```shell
d:\dev\with space\dropbox-sdk-php-master\examples>php web-file-browser.php
The filename, directory name, or volume label syntax is incorrect.

d:\dev\with space\dropbox-sdk-php-master\examples>php ./web-file-browser.php
The system cannot find the path specified.
```

After:
```shell
d:\dev\with space\dropbox-sdk-php-master\examples>php ./web-file-browser.php
PHP 7.0.9 Development Server started at Wed Feb  8 18:48:52 2017
Listening on http://localhost:5000
Document root is D:\!_data\Dropbox (GSRO)\Users\Gabi\Downloads\dropbox-sdk-php-master\examples
Press Ctrl-C to quit.
```

**Comment by greg-db** [comment]
Thanks for submitting this! Note that this SDK uses the [deprecated](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/) API v1 though.

**Comment by cakoose** [comment]
Weird, I thought `escapeshellarg` was supposed to do the right thing.  Just so I understand what's happening, can you take the original version of the code and add the following right before the `proc_open` call:

```
    print("version: ".PHP_VERSION."\n");
    print("cmd: ".$cmd."\n");
```

And then run it and copy/paste the output?

**Comment by gabidj** [comment]
```
>php web-file-browser.php
version: 7.0.9
cmd: "D:\xampp\php\php.exe" -S localhost:5000 "web-file-browser.php"
The filename, directory name, or volume label syntax is incorrect.
```

**Comment by cakoose** [comment]
Hmm, looks like this might be a bug in `proc_open`: https://bugs.php.net/bug.php?id=49139

That bug report suggests either surrounding the whole thing in double quotes or passing `bypass_shell`.  The script below tries those workarounds.  Can you run it and send me the output?

```
<?php

function check_proc_open($cmd, $options) {
    $descriptors = array(
        0 => array("pipe", "r"),  // Process' stdin.  We'll just close this right away.
        1 => STDOUT,              // Relay process' stdout to ours.
        2 => STDERR,              // Relay process' stderr to ours.
    );
    $proc = proc_open($cmd, $descriptors, $pipes, null, $options);
    fclose($pipes[0]);  // Close the process' stdin.
    $exit_code = proc_close($proc);  // Wait for process to exit.
    print("EXIT: $exit_code\n\n");
}

function check($cmd) {
    print("========= $cmd ==========\n");
    print("----- system -----\n");
    system($cmd, $exit_code);
    print("EXIT: $exit_code\n\n");

    print("----- proc_open -----\n");
    check_proc_open($cmd, array());

    print("----- proc_open(bypass_shell) -----\n");
    check_proc_open($cmd, array("bypass_shell" => true));
}

$b = PHP_BINARY;

check("$b --version");
check(escapeshellarg($b)." --version");
check('"'.escapeshellarg($b)." --version".'"');
check(escapeshellarg(escapeshellarg($b)." --version"));
```

**Pull request closed without merging**
