### PR TITLE
Clean up Path::checkArg

### PR DESCRIPTION
**Pull request by sergeyklay**
The same as 41fea22b293d0a78e24776a2f7eafb6619f65d2b

### CODE REVIEW

**Comment by cakoose** [comment]
This change already made it into `master`, right?

**Comment by sergeyklay** [comment]
Yes

**Comment by cakoose** [comment]
So what is the pull request for?  Can I close it?

**Comment by sergeyklay** [comment]
No no :) Let me show:

I have made this changes: https://github.com/dropbox/dropbox-sdk-php/blob/master/lib/Dropbox/Path.php#L164-L170

Now I suggest to clean this method: https://github.com/dropbox/dropbox-sdk-php/blob/master/lib/Dropbox/Path.php#L136-L142

**Comment by cakoose** [comment]
Oh, got it.

**Pull request closed without merging**
